### ISSUE TITLE
OS Command Injection

### ISSUE THREAD

**Issue by 20esaua** [kkeglje/LearningPython#1]
Er, multiple instances of OS command injection, just Ctrl+F for `os.system`:
https://github.com/kelj0/LearningPython/blob/b4b686f867ff6b06c38fda23b9a7751746106da4/SmallProjects/Define/define.py

**Comment by kelj0** [comment]
![image](https://user-images.githubusercontent.com/35850075/63944086-31f89280-ca71-11e9-851e-6605e977e79d.png)
I dont see command injection here (i'm on Debian 10). I'll install few more distros to the vbox and try there.

**Comment by kelj0** [comment]
![Peek 2019-08-29 17-26](https://user-images.githubusercontent.com/35850075/63953779-45f8c000-ca82-11e9-842e-967f67d456f2.gif)
Whoa, i've found it (if your issue was for that command injection). [I've fixed it](https://github.com/kelj0/LearningPython/commit/2563088bf44f4d5e7f7d65f3c41f12fdaef4a1e4) thank you for issue :)
